on: [
  push,
  pull_request
]

name: Run tests

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: test --stacktrace
